package gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class FramePrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        panelAlgoritimos = new javax.swing.JPanel();
        labelBotoes = new javax.swing.JLabel();
        rdMover = new javax.swing.JRadioButton();
        rdDDA = new javax.swing.JRadioButton();
        rdBresenham = new javax.swing.JRadioButton();
        rdCircunferencia = new javax.swing.JRadioButton();
        rdCohenSutherland = new javax.swing.JRadioButton();
        rdLianBarsky = new javax.swing.JRadioButton();
        rdRotacionar = new javax.swing.JRadioButton();
        rdAlterarEscala = new javax.swing.JRadioButton();
        scrollPaneImagem = new javax.swing.JScrollPane();
        panelImagem = new gui.PanelImagem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1052, 602));
        setResizable(false);

        labelBotoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelBotoes.setText("Algoritimos");

        buttonGroup.add(rdMover);
        rdMover.setText("Translação");
        rdMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMoverActionPerformed(evt);
            }
        });

        buttonGroup.add(rdDDA);
        rdDDA.setText("Reta DDA");
        rdDDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDDAActionPerformed(evt);
            }
        });

        buttonGroup.add(rdBresenham);
        rdBresenham.setText("Reta Bresenham");
        rdBresenham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBresenhamActionPerformed(evt);
            }
        });

        buttonGroup.add(rdCircunferencia);
        rdCircunferencia.setText("Circunferência");
        rdCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCircunferenciaActionPerformed(evt);
            }
        });

        buttonGroup.add(rdCohenSutherland);
        rdCohenSutherland.setText("Recorte Cohen-Sutherland");
        rdCohenSutherland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCohenSutherlandActionPerformed(evt);
            }
        });

        buttonGroup.add(rdLianBarsky);
        rdLianBarsky.setText("Recorte Lian-Barsky");
        rdLianBarsky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLianBarskyActionPerformed(evt);
            }
        });

        buttonGroup.add(rdRotacionar);
        rdRotacionar.setText("Rotacionar");
        rdRotacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRotacionarActionPerformed(evt);
            }
        });

        buttonGroup.add(rdAlterarEscala);
        rdAlterarEscala.setText("Alterar Escala");
        rdAlterarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlterarEscalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlgoritimosLayout = new javax.swing.GroupLayout(panelAlgoritimos);
        panelAlgoritimos.setLayout(panelAlgoritimosLayout);
        panelAlgoritimosLayout.setHorizontalGroup(
            panelAlgoritimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlgoritimosLayout.createSequentialGroup()
                .addGroup(panelAlgoritimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlgoritimosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(labelBotoes))
                    .addGroup(panelAlgoritimosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rdRotacionar)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(panelAlgoritimosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlgoritimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdLianBarsky)
                    .addComponent(rdCohenSutherland)
                    .addComponent(rdCircunferencia)
                    .addComponent(rdBresenham)
                    .addComponent(rdDDA)
                    .addComponent(rdMover)
                    .addComponent(rdAlterarEscala))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAlgoritimosLayout.setVerticalGroup(
            panelAlgoritimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlgoritimosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBotoes)
                .addGap(18, 18, 18)
                .addComponent(rdMover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdDDA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBresenham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdCircunferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdCohenSutherland)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdLianBarsky)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdRotacionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdAlterarEscala)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImagemLayout = new javax.swing.GroupLayout(panelImagem);
        panelImagem.setLayout(panelImagemLayout);
        panelImagemLayout.setHorizontalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelImagemLayout.setVerticalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        scrollPaneImagem.setViewportView(panelImagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAlgoritimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneImagem))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAlgoritimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPaneImagem)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMoverActionPerformed
        panelImagem.setDesenho( panelImagem.idMover );
    }//GEN-LAST:event_rdMoverActionPerformed

    private void rdDDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDDAActionPerformed
        panelImagem.setDesenho( panelImagem.idDDA );
    }//GEN-LAST:event_rdDDAActionPerformed

    private void rdBresenhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBresenhamActionPerformed
        panelImagem.setDesenho( panelImagem.idBresenham );
    }//GEN-LAST:event_rdBresenhamActionPerformed

    private void rdCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCircunferenciaActionPerformed
        panelImagem.setDesenho( panelImagem.idCircunferencia );
    }//GEN-LAST:event_rdCircunferenciaActionPerformed

    private void rdCohenSutherlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCohenSutherlandActionPerformed
        panelImagem.apagaRecorte();
        panelImagem.setDesenho( panelImagem.idCohenSutherland );
    }//GEN-LAST:event_rdCohenSutherlandActionPerformed

    private void rdRotacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRotacionarActionPerformed
        panelImagem.setDesenho( panelImagem.idRotacionar );
    }//GEN-LAST:event_rdRotacionarActionPerformed

    private void rdLianBarskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLianBarskyActionPerformed
        panelImagem.apagaRecorte();
        panelImagem.setDesenho( panelImagem.idLianBarsky );
    }//GEN-LAST:event_rdLianBarskyActionPerformed

    private void rdAlterarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlterarEscalaActionPerformed
        panelImagem.setDesenho( panelImagem.idEscala );
    }//GEN-LAST:event_rdAlterarEscalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel labelBotoes;
    private javax.swing.JPanel panelAlgoritimos;
    private gui.PanelImagem panelImagem;
    private javax.swing.JRadioButton rdAlterarEscala;
    private javax.swing.JRadioButton rdBresenham;
    private javax.swing.JRadioButton rdCircunferencia;
    private javax.swing.JRadioButton rdCohenSutherland;
    private javax.swing.JRadioButton rdDDA;
    private javax.swing.JRadioButton rdLianBarsky;
    private javax.swing.JRadioButton rdMover;
    private javax.swing.JRadioButton rdRotacionar;
    private javax.swing.JScrollPane scrollPaneImagem;
    // End of variables declaration//GEN-END:variables
}
